### PR TITLE
ENH: Implement displacement chart as a plugin

### LINKED ISSUE #84: Add motion summary plots
Let's add 3 plots that would report motion in IS/LR/AP directions relative to the initial position of the prostate, based on the registration result. To do this, we can calculate the centroid of the whole gland segmentation, and for each registration apply the accepted registration result (whatever was accepted - either rigid or b-spline) to get a new point for each of the plots.

### PR DESCRIPTION
**Pull request by Kmacneil0102**
Fixes #84.

- Displays the I/S, P/A, L/R and 3-D displacement as individual plots for the currently selected target, for all series with approved registrations

@fedorov Currently chart only displayed during the Overview step, do you think it might be beneficial to also display it in the Evaluation step?

### CODE REVIEW

**Comment by che85** [comment]
It definitely makes sense to me to add the displacement charts to the evaluation step...

**Comment by fedorov** [comment]
Yes, I agree it makes sense to add to evaluation.

Show me a demo tomorrow when we meet!

**Comment by che85** [comment]
@fedorov Kemal approved of the charts. @Kmacneil0102 is going to fix some minor issues and then we are going to merge this.

**Comment by fedorov** [comment]
> Kemal approved of the charts.

What exactly did he say? Did he say that he is ok to have them shown, or did he say they might potentially be useful?

**Comment by che85** [comment]
He said it might be useful for research purposes but not during the procedure because an earlier study already proofed that most displacement happens in the I/S plane. I segmented the prostate when @Kmacneil0102 was talking with Kemal, so I was listening only with one ear... Kyle, did I forgot or misunderstood anything?

**Comment by Kmacneil0102** [comment]
@che85 That's basically what he said! He said that the displacement wasn't really something that they worry about during the procedures (at which point he mentioned the I/S plane having the most significant displacement), but that he thinks it would be something quite useful for research purposes.

**Pull request merged**
