### PR TITLE
WIP: writing hole to arduino upon target selection (issue #294)

### LINKED ISSUE #294: Add interface to get a list of computed zFrame indexes for the selected result
A visiting researcher from Germany would like to get a list of computed zFrame holes for using it on a prototype in order to be able to visually display which hole to use via a printable phosphoric light source

### PR DESCRIPTION
**Pull request by che85**
* implemented for overview and evaluation step

using https://github.com/pyserial/pyserial with BSD license for sending the targets to arduino

fixes #294

### CODE REVIEW

**Comment by fedorov** [comment]
I am not sure it is a good idea to add this to the core of the module. This is a c code, which may cause issues with maintenance and cross-platform builds. It serves a very narrow purpose. Let's discuss this next Tuesday.

**Comment by lassoan** [comment]
In general, we don't connect Slicer directly to any special hardware. One option is to use OpenIGTLink to send messages to PlusServer and PlusServer forwards them through serial port to Arduino (this feature is already implemented, we use arduinos through PlusServer from Slicer). An additional advantage is that you don't have to connect the Arduino directly to the Slicer computer and if Slicer disconnects.

Disadvantage is of course that you have to start an additional application (PlusServer can automatically reconnect, and Slicer and PlusServer can be launched in any order, so it doesn't add too much complication).

**Comment by fedorov** [comment]
I also wanted to suggest openigtlink instead of this serial code.

**Comment by che85** [comment]
Yeah i noticed one post[1] about using OpenIGTLink and PlusServer but I thought it might be too complicated to setup for MacOS. Am I right with that assumption? The last time I wanted to use PlusServer on MacOS, I needed to compile it by myself. Not sure if something changed?

[1] http://slicer-devel-archive.65872.n3.nabble.com/Access-serial-ports-through-slicer-extension-td4038359.html#a4038360

**Comment by fedorov** [comment]
How about we ask Anke to explore this and report back?

**Comment by lassoan** [comment]
Currently, general serial device in Plus is only supported on Windows, so the simplest is to plug the Arduino in a windows computer that's already there or buy a mini PC for $100-200 that you can install Plus on (like these http://a.co/4s7Px6D, http://a.co/0z29lK9). You could connect additional devices, sensors, cameras, etc. and you could use wifi instead of connecting the Arduino directly with the Slicer computer.

If you prefer Linux, we can add Linux serial device support to Plus in about 1-2 weeks.

We could even add Mac serial line support if you must run Slicer and connect Arduino to the same Mac and you would use Plus.

**Comment by che85** [comment]
Yeah sounds good to me. I will send her an email and cc you.

**Comment by che85** [comment]
@lassoan The problem is, that Anke is here from Germany and she just wants to use that for her study. She is only staying here until the end of August so I don't know if there is time for doing all this because she is busy with designing the study.

**Comment by lassoan** [comment]
Setting this up with a Windows PC that is already there should take a few hours. If you need yo go out and buy a new mini PC and set it up then maybe it would take a day.

O course it's difficult to tell if it's a good option without knowing what the end goal is. Would you like to have a small display in the OR? If that's the case, it may be easier to just connect a USB display (http://a.co/1wLMRkp) or mini projector (http://a.co/6YGPEhj) as a secondary screen where Slicer can directly display anything.

**Comment by che85** [comment]
I am going to close this PR since we are not going to merge it anyway.

**Comment by ankevr** [comment]
I'm new to Slicer and it's possibilities and plugins, I did not know about the OpenIGTLink plugin (and I have a Mac) and I did not expect the serial communication to be a maintained functionality. I was just looking for an option to communicate as directly as possible with the prototypical EL display controller (the arduino) to reduce the points where problems could occur. My primary goal is for now is just to do a feasibility study with the prostate template in form of a user study. To have a more real scenario I wanted the connection to SliceTracker. I will discuss  the OpenIGTLink possiblity with Junichi.

**Comment by fedorov** [comment]
> My primary goal is for now is just to do a feasibility study with the prostate template in form of a user study.

Then perhaps this PR would already be sufficient for this task, or at the very least serve as a very good start?

**Comment by lassoan** [comment]
For initial prototyping just use anything that works.

If you are thinking about implementing a sustainable solution, which can be deployed easily in various environments, then having an OpenIGTLink interface on your device would be very convenient. Hardware interface is simpler (there is no strict point-to-point connection requirement between the navigation computer and the custom display); software interface is simples (as OpenIGTLink communication is already supported in many surgical navigation applications/frameworks, such 3D Slicer, MevisLab, MITK, NifTK, CustusX).

A commonly used and easy to implement solution is to add a Raspberry Pi or other mini PC that runs Plus or another simple OpenIGTLink server that communicates with the Arduino.

**Pull request closed without merging**
