### PR TITLE
ENH: Progressbar for bias correction and (re)registration added

### PR DESCRIPTION
**Pull request by che85**

### CODE REVIEW

**Comment by che85** [comment]
fixed. Fixes Issue #30

**Comment by fedorov** [comment]
Is this "closed->reopened->merged" intentional or accidental?

**Comment by che85** [comment]
Yes I forgot to merge :)

**Comment by fedorov** [comment]
We really need to sit down together and go over the git workflow! What you are doing looks confusing, and I think it may also be confusing to you! I think I didn't make myself very clear during the skype call today, or I am missing something.

**Pull request merged**
