### PR TITLE
Moved code to SlicerProstate, preop preview while segmenting, target modification saved and loadable

### LINKED ISSUE #4: File ouput in PCampReview folder structure

### LINKED ISSUE #89: Provide preop prostate segmentation preview during intraop prostate segmentation
It would be pretty useful for the user, if he/she could have the possibility to see the prostate segmentation (in preop data or cover prostate if retrying) to be able to get an idea of how the "previous" segmentation looks like. 

Especially useful is that, when preop prostate segmentation was done by another user.

Therefore we could offer a button for showing/hiding previous segmentation (then maybe switching to side by side view)

### LINKED ISSUE #106: Manual adjustment of the targets
If registration fails, it should be possible and easy to adjust the locations of the targets in 3d. For this, need to:
 - switch to either 3-over-3 layout (pre-procedural t2 in the top row, cover prostate in the bottom), or to 2-over-2 layout (axial, sag and cor for cover prostate and axial for planning t2)
 - when target is clicked in the target list, synchronize the cover prostate views to the positions of the target in cover prostate, and at the same time synchronize positions of the planning image(s) to the same target there
 - annotate slice viewers preop/intraop
 - when target is moved in intraop, synchronize all intraop views to the new location
 - "lock" preop target to prevent accidental modification

### LINKED ISSUE #136: Switching layouts in evaluation step should enable/disable crosshair automatically
Switching to FourUp: enable crossshair
Switching to SideBySide: disable crosshair

### LINKED ISSUE #137: ZFrame Template visibility
Switching to FourUp layout and enabling ZFrame template, it is correctly displayed in all (red, yellow, green) slice views.  Swtiching back should only enable it in yellow slice view what is currently not the case because it is also visible in red slice view.

### LINKED ISSUE #139: All series that come from the scanner should be loaded
Actions (skip/track) and their automatic applications should be defined only for the recognized series, but any series received from the scanner should be in the scene in case operator needs to display it.

### LINKED ISSUE #140: Support w/l modification of the Fg layer
Suggested approach:

1) add button to switch to w/l mode (if not hard, change the mouse icon when changed)
2) depending on the transparency setting, round the transparency to either 0 or 1
3) modify w/l for either Fg or Bg depending on the transparency setting
4) user has to explicitly turn off w/l mode

### LINKED ISSUE #141: Add SeriesDescription configuration file
It should be possible to configure what is the expected SeriesDescription value for z-frame, cover prostate, needle confirmation images.

### LINKED ISSUE #142: When running SliceTracker first time user has to select case root
- If no case root could be retrieved from settings, newCaseButton and openCaseButton should be disabled.

### LINKED ISSUE #143: Switching to FourUp in overview step should set background only and link viewers
User should be able to set foreground as required

### LINKED ISSUE #144: Update Config file based on wikipage
https://github.com/SlicerProstate/SliceTracker/wiki/Configuration-File

### PR DESCRIPTION
**Pull request by che85**
fixes #4 
fixes #89
fixes #106
fixes #136 
fixes #137
fixes #139 
fixes #140
fixes #141 
fixes #142 
fixes #143
fixes #144 
depending on SlicerProstate/SlicerProstate/pull/13

### CODE REVIEW

**Comment by fedorov** [comment]
Shouldn't there be a dependency on SlicerProstate here too?

**Comment by fedorov** [comment]
Maybe I missed it...

**Comment by che85** [comment]
yeah right. done.

**Comment by che85** [comment]
@fedorov For any reason SliceTracker is not loaded when adding SlicerProstate as a dependency

**Comment by fedorov** [comment]
any errors in the console?

**Comment by che85** [comment]
No nothing. I compiled SlicerProstate and selected the scripted module directory. Maybe anything missing in the module name? I am at a case now, will investigate time later

**Comment by che85** [comment]
@fedorov Created hidden SlicerProstateUtils module and set dependency

**Comment by fedorov** [comment]
> @fedorov Created hidden SlicerProstateUtils module and set dependency

cross-linking for the reference https://github.com/SlicerProstate/SlicerProstate/pull/16

**Comment by che85** [comment]
@fedorov You can merge this PR. I am done with the most issues. I just want to look again over the code and see if i can optimize or simplify something. And the we need to do Testing Testing Testing

**Comment by fedorov** [comment]
wow, this is a lot!

**Comment by fedorov** [comment]
I admit, no time to do a meaningful review or testing!.. :(

**Comment by che85** [comment]
No problem. We just need to make sure that everything is fine when we plan to use it in production mode. 👍

**Pull request merged**
