### PR TITLE
ENH: added TargetSelectionEvent to session (issue #284):

### PR DESCRIPTION
**Pull request by che85**
fixes #297 

@Kmacneil0102 the following code should be added to your TargetDisplacementPlugin

```
self.session.addEventObserver(self.session.TargetSelectionEvent, self.onTargetSelectionChanged)

@vtk.calldata_type(vtk.VTK_STRING)
def onTargetSelectionChanged(self, caller, event, callData):
  targetListId, index = ast.literal_eval(callData)
  if not targetListId or index == -1:
    # hide displacement widget
  else:
    # show displacement widget and set compute displacement
    targetList = slicer.mrmlScene.GetNodeByID(targetListId)
    print "%s, %s " % (targetListId, index)
```

### CODE REVIEW

**Comment by che85** [comment]
@Kmacneil0102 I will actually change the parameters delivered for the targetlist to:

```
@vtk.calldata_type(vtk.VTK_STRING)
def onTargetSelectionChanged(self, caller, event, callData):
  targetListId, info = ast.literal_eval(callData)
  if not targetListId or info['index'] == -1:
    # hide displacement widget
  else:
    # show displacement widget and set compute displacement
    targetList = slicer.mrmlScene.GetNodeByID(targetListId)
    print "%s, %s " % (targetListId, info['index'])
```

Why I want to do that? In order to be able to send the computed coordinates to a device, I want to make sure to have a dictionary holding those information besides the selected index.

**Comment by che85** [comment]
@Kmacneil0102 just added the commit. 

info provides the following example information:

`vtkMRMLMarkupsFiducialNode8, {'index': 0, 'hole': '(E, -1)', 'depth': '13.3'} `

Not sure if that could also be useful for you but at least it can be used for displaying the calculated whole and depth visually on a display that might be used in the OR

**Comment by che85** [comment]
Actually I could just put everything into one dictionary and add the nodeId as another key

**Comment by Kmacneil0102** [comment]
That way the call data would just return the dictionary with the target node and index as keys in the dictionary? Sounds good to me!

**Comment by che85** [comment]
Yes exactly...

**Comment by che85** [comment]
I am going to merge this so you can work with the master branch

**Pull request merged**
